openapi: 3.0.1
info:
  title: Blogging Platform API
  description: API for managing blog posts
  version: 1.0.0

paths:
  /api/v1/posts:
    get:
      summary: Get all posts
      operationId: getAllPosts
      tags:
        - posts
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostResponse'

    post:
      summary: Create a new post
      operationId: createNewPost
      tags:
        - posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post created

  /api/v1/posts/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'
    get:
      summary: Get a post by ID
      operationId: getPost
      tags:
        - posts
      responses:
        '200':
          description: Post details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'

    put:
      summary: Update a post by ID
      operationId: updatePost
      tags:
        - posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated

    delete:
      summary: Delete a post by ID
      operationId: deletePost
      tags:
        - posts
      responses:
        '204':
          description: Post deleted

components:
  parameters:
    idParam:
      in: path
      name: id
      required: true
      description: Unique post ID
      schema:
        type: integer
        format: int64

  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - id
        - title
        - content


    PostResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: data-time
      required:
        - id
        - title
        - content
        - createdAt
        - updatedAt



